import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ChevronDown, ChevronLeft, ChevronRight, Heart, MapPin, Menu, Search, ShoppingBag, Sparkles, Star, X} from 'lucide-react';
import './styles.css';

const categories=['All','PS5 Console','Xbox Console','VR','Big Screen Gaming','Racing Wheel','PS5 Games'];
const products=[
 {name:'PS5 All in one Combo + 2 Controllers',cat:'PS5 Console',desc:'PS5 console with 2 controllers and 100+ games.',price:499,booked:394,rating:4.5,badge:'Trending',img:'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?auto=format&fit=crop&w=900&q=80'},
 {name:'PS5 Mega Racing Wheel Combo',cat:'Racing Wheel',desc:'Race like a pro with racing wheel and premium games.',price:699,booked:196,rating:4.8,badge:'',img:'https://images.unsplash.com/photo-1592840062661-7c6d0f5f2e8c?auto=format&fit=crop&w=900&q=80'},
 {name:'Xbox Series S + 2 Controllers',cat:'Xbox Console',desc:'Compact Xbox setup for multiplayer gaming.',price:449,booked:178,rating:4.7,badge:'Popular',img:'https://images.unsplash.com/photo-1621259182978-fbf93132d53d?auto=format&fit=crop&w=900&q=80'},
 {name:'Meta Quest VR Gaming Set',cat:'VR',desc:'Immersive VR entertainment for your next game night.',price:799,booked:128,rating:4.6,badge:'',img:'https://images.unsplash.com/photo-1622979135225-d2ba269cf1ac?auto=format&fit=crop&w=900&q=80'},
 {name:'PS5 + Projector Big Screen Combo',cat:'Big Screen Gaming',desc:'Bring the big-screen gaming experience home.',price:999,booked:169,rating:4.8,badge:'Trending',img:'https://images.unsplash.com/photo-1605890233737-0f7a6d3b1e9a?auto=format&fit=crop&w=900&q=80'},
 {name:'FC 25 + 2 Controllers Combo',cat:'PS5 Games',desc:'Football nights with a subscription-packed setup.',price:549,booked:241,rating:4.8,badge:'',img:'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=900&q=80'},
 {name:'PS5 + GTA V + 1 Controller',cat:'PS5 Games',desc:'Explore Los Santos with PS5 performance.',price:499,booked:178,rating:4.9,badge:'',img:'https://images.unsplash.com/photo-1605901309584-818e25960a8f?auto=format&fit=crop&w=900&q=80'},
 {name:'PS5 + Spider-Man 2 + Controller',cat:'PS5 Games',desc:'Swing through New York with Spider-Man 2.',price:549,booked:218,rating:4.5,badge:'',img:'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=900&q=80'}
];
const faqs=[
 ['How can I rent from SharePal?','Choose your product, select your rental dates, enter your delivery details and complete checkout. We deliver the equipment to your doorstep.'],
 ['If I rent multiple products, do I need to extend the rental duration for all or partial extension is possible?','You can manage products independently based on availability and rental duration. Contact support if you need an extension.'],
 ['What is the minimum rental period?','Most products can be rented for a minimum of 3 days. The exact minimum is shown during booking.'],
 ['When does the rental start?','Your rental period begins according to the delivery date selected during checkout.'],
 ['What will be the condition of the products at the time of delivery?','Every product goes through quality checks before delivery and is cleaned and prepared for use.']
];
const reviews=[
 ['SB','Satyaki','Kolkata • Trekking Gear','I would recommend SharePal for anybody looking to rent trekking gears. On time delivery, very good product condition and a transparent deposit return policy.'],
 ['AS','Afrana','Bangalore • Gaming Console','Have used their services twice now. They never disappoint. Quick responses, polite, transparent, hassle free and great products.'],
 ['AA','Amal','Bangalore • Gaming Console','I am a regular customer and order PS4. It is very affordable and booking an order is super easy and user friendly.'],
 ['MM','Manish','Mumbai • Gaming Console','I like the way SharePal works and really enjoyed the PS4. Will order again. Thanks SharePal!']
];
function App(){
 const [cat,setCat]=useState('All'); const [wish,setWish]=useState([]); const [faq,setFaq]=useState(null); const [menu,setMenu]=useState(false); const [review,setReview]=useState(0); const [start,setStart]=useState(''); const [end,setEnd]=useState('');
 const filtered=useMemo(()=>cat==='All'?products:products.filter(p=>p.cat===cat),[cat]);
 useEffect(()=>{const t=setInterval(()=>setReview(r=>(r+1)%reviews.length),5000);return()=>clearInterval(t)},[]);
 return <div className="app">
  <header className="nav"><div className="nav-inner"><button className="mobile-btn" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button><div className="logo">share<span>pal</span><i>.</i></div><div className="location"><MapPin size={16}/><span>Bangalore</span><ChevronDown size={15}/></div><nav className={menu?'open':''}><a href="#products">Gaming</a><a href="#products">Categories</a><a href="#why">How it works</a><a href="#faq">FAQs</a></nav><div className="nav-actions"><Search size={20}/><span className="login">Login</span><ShoppingBag size={20}/></div></div></header>
  <main>
   <section className="hero"><div className="hero-copy"><div className="eyebrow"><Sparkles size={15}/> GAMING GADGETS</div><h1>Gaming gadgets<br/><em>on rent</em></h1><p>Rent the latest gaming gadgets from PS5, Xbox, Oculus VR, Racing Wheel and more.</p><div className="trust"><span>✓ Zero security deposit</span><span>✓ Free delivery</span><span>✓ Lowest price guarantee</span></div></div><div className="hero-art"><div className="orb"></div><div className="console-card"><div className="console"></div><div className="controller c1"></div><div className="controller c2"></div></div><div className="float-tag">LEVEL UP<br/><small>without buying</small></div></div></section>
   <section className="datebar"><div><b>Select rental dates to view prices</b><small>Choose when you want your gear delivered</small></div><div className="date-fields"><label>From<input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><span>→</span><label>To<input type="date" value={end} min={start} onChange={e=>setEnd(e.target.value)}/></label><button>SELECT</button></div></section>
   <section className="category-section"><div className="section-heading"><div><p className="kicker">EXPLORE</p><h2>Gaming Consoles</h2><p>Choose your favourite way to play.</p></div></div><div className="tabs">{categories.map(c=><button className={cat===c?'active':''} onClick={()=>setCat(c)} key={c}>{c}</button>)}</div></section>
   <section className="products" id="products"><div className="product-head"><div><h2>{cat==='All'?'Gaming gadgets':cat} on rent</h2><p>{filtered.length} items • Bangalore</p></div><button className="sort">Sort by <b>Popularity</b><ChevronDown size={16}/></button></div><div className="grid">{filtered.map((p,i)=><article className="product" key={p.name}><div className="pic">{p.badge&&<span className="badge">{p.badge}</span>}<button className="heart" onClick={()=>setWish(w=>w.includes(i)?w.filter(x=>x!==i):[...w,i])}><Heart size={19} fill={wish.includes(i)?'currentColor':'none'}/></button><img src={p.img} alt={p.name}/></div><div className="product-body"><h3>{p.name}</h3><p>{p.desc}</p><div className="meta"><span><Star size={14} fill="currentColor"/> {p.rating}</span><span>{p.booked} booked this month</span></div><div className="price-row"><div><small>from</small><strong>₹{p.price}</strong><small>/ 3 days</small></div><button>Select Dates</button></div></div></article>)}</div></section>
   <section className="promise" id="why"><div><p className="kicker">THE SHAREPAL PROMISE</p><h2>Rent with peace.</h2><p>Premium gear, transparent pricing and a quality check before every delivery.</p></div><div className="promise-grid"><div><b>01</b><h3>12 Point Quality Check</h3><p>Every product is checked before delivery.</p></div><div><b>02</b><h3>Lowest Price Guarantee</h3><p>Great gear without the buying price tag.</p></div><div><b>03</b><h3>Prompt Help & Support</h3><p>Real people ready to help from 10am–10pm.</p></div></div></section>
   <section className="faq" id="faq"><div className="section-title"><p className="kicker">NEED TO KNOW</p><h2>Frequently Asked Questions</h2></div><div className="faq-list">{faqs.map(([q,a],i)=><div className={'faq-item '+(faq===i?'show':'')} key={q}><button onClick={()=>setFaq(faq===i?null:i)}><span>{q}</span><ChevronDown size={20}/></button><div className="answer">{a}</div></div>)}</div><button className="outline">View more FAQ's</button></section>
   <section className="reviews"><div className="section-title"><p className="kicker">LOVED BY RENTERS</p><h2>Served more than 1 Lakh Orders</h2></div><div className="review-wrap"><button onClick={()=>setReview((review-1+reviews.length)%reviews.length)}><ChevronLeft/></button><div className="review-card"><div className="avatar">{reviews[review][0]}</div><div className="quote">“</div><p>{reviews[review][3]}</p><div className="stars">★★★★★</div><b>{reviews[review][1]}</b><small>{reviews[review][2]}</small></div><button onClick={()=>setReview((review+1)%reviews.length)}><ChevronRight/></button></div><div className="dots">{reviews.map((_,i)=><button key={i} className={i===review?'on':''} onClick={()=>setReview(i)}/>)}</div></section>
   <section className="stats"><div><strong>250Cr+</strong><span>Saved Together</span></div><div><strong>4.5M Kg</strong><span>CO₂e Emissions Saved</span></div><div><strong>100K+</strong><span>Products in Circulation</span></div></section>
   <section className="related"><p className="kicker">EXPLORE MORE</p><h2>More things to rent</h2><div className="related-grid">{['Action Cameras','Cameras','Trekking Gear','Riding Gear','Creator Gear','Winter Wear','Camping Gear','Audio Visual Equipment'].map((x,i)=><div key={x}><div className={'rel-img r'+i}></div><b>{x}</b><span>Explore category →</span></div>)}</div></section>
  </main>
  <footer><div className="footer-main"><div><div className="logo">share<span>pal</span><i>.</i></div><p>Rent the gear. Own the experience.</p></div><div><b>About</b><a>Why SharePal</a><a>Careers</a><a>FAQs</a></div><div><b>Information</b><a>How it works?</a><a>Verification</a><a>Cancellation Policy</a></div><div><b>Need Help</b><a>+91 76192 20543</a><a>care@sharepal.in</a></div></div><div className="copyright">© 2026 SharePal. Built as a frontend recreation assignment.</div></footer>
 </div>
}
createRoot(document.getElementById('root')).render(<App/>);
